version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './:/var/www/html'
    ports:
      - '${FORWARD_APP_PORT:-80}:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - shorter
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_DATABASE: '${DB_DATABASE:-shorter}'
      MYSQL_USER: '${DB_USERNAME:-shorter}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-shorter}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'shorter_mysql:/var/lib/mysql'
    networks:
      - shorter
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD-shorter}" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'shorter_redis:/data'
    networks:
      - shorter
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  shorter:
    driver: bridge
volumes:
  shorter_mysql:
    driver: local
  shorter_redis:
    driver: local
